### ISSUE TITLE
Cannot customize primary color

### ISSUE THREAD

**Issue by oranges13** [pikock/bootstrap-magic#76]
If there is a way, I could not find it -- but in the Brand colors drop down, there is no way to customize the primary color with a hex code. I do not want to reconfigure one of the color variables (such as $blue) because of the utility that provides, however I need to use a specific hex code for our brand colors as our primary color and build from there.

I attempted to use the "import" function to add my own variables, but they are added at the end of the script and are not available to the brand selection area.

As it is, there is no way to add a new variable and assign it in the $theme-colors selection.

**Comment by WebDragon** [comment]
under Brand Colors, the $theme-colors section, you can replace `(primary: $blue, secondary: $gray-600, success: $green, info: $cyan, warning: $yellow, danger: $red, light: $gray-100, dark: $gray-800)`

with 
`(primary: #C0FFEE, secondary: #F1EECE, success: #10CA1E, info: #10ADED, warning: #DEFACE, danger: #BA1B0A, light: $gray-100, dark: $gray-800)`

so I don't see what the problem is. there's just no SEPARATE field to put those values in, but this does the trick just fine. it's just grouped like this because these are your theme colors.

**Comment by oranges13** [comment]
Hey, thanks for this! It works!

Anyone else having issues getting things to work you can refer to theme colors using the `theme-color('primary')` function within other settings.
